name: Build and publish Docker images

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - id: app
            context: .
            file: docker/Dockerfile.app
          - id: docreader
            context: .
            file: docker/Dockerfile.docreader
          - id: frontend
            context: ./frontend
            file: ./frontend/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute lowercase image name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          docker-images: false
          large-packages: true
          swap-storage: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}-${{ matrix.id }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build (no push) for PR/dispatch
        if: ${{ (github.event_name != 'push' || (github.event_name == 'push' && !(github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')))) && matrix.id != 'docreader' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: false
          platforms: linux/amd64
          build-args: |
            ${{ matrix.id == 'app' && format('GOPRIVATE_ARG={0}', secrets.GOPRIVATE) || '' }}
            ${{ matrix.id == 'app' && format('GOPROXY_ARG={0}', secrets.GOPROXY) || '' }}
            ${{ matrix.id == 'app' && 'GOSUMDB_ARG=off' || '' }}
            ${{ matrix.id == 'docreader' && 'PLATFORM=linux/amd64' || '' }}
          tags: local/${{ matrix.id }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push for main/tags
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) && matrix.id != 'docreader' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          platforms: linux/amd64
          build-args: |
            ${{ matrix.id == 'app' && format('GOPRIVATE_ARG={0}', secrets.GOPRIVATE) || '' }}
            ${{ matrix.id == 'app' && format('GOPROXY_ARG={0}', secrets.GOPROXY) || '' }}
            ${{ matrix.id == 'app' && 'GOSUMDB_ARG=off' || '' }}
            ${{ matrix.id == 'docreader' && 'PLATFORM=linux/amd64' || '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}-${{ matrix.id }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}-${{ matrix.id }}:buildcache,mode=max

      # Docreader is extremely heavy; run only on demand via input or label in future
      - name: Skip heavy docreader on PR/dispatch
        if: ${{ matrix.id == 'docreader' }}
        run: echo "Skipping docreader build to avoid runner disk exhaustion"
